version=1
file=hw_platform=/run/sensors-platform/hw_platform
file=platform_subtype=/run/sensors-platform/platform_subtype
file=platform_subtype_id=/run/sensors-platform/platform_subtype_id
file=platform_version=/run/sensors-platform/platform_version
file=soc_id=/run/sensors-platform/soc_id
file=revision=/run/sensors-platform/revision
file=input=json.lst
file=output=/persist/sensors/registry/registry
file=config=/vendor/etc/sensors/config
